
import java.awt.Component;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.io.UnsupportedEncodingException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.util.ArrayList;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author NABAIN
 */
public class frmITMode extends javax.swing.JFrame {

    /**
     * Creates new form frmITMode
     */
    public frmITMode() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAddEmp = new javax.swing.JButton();
        btnViewModifyEmp = new javax.swing.JButton();
        btnCreateDailyRpt = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("IT Mode");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnAddEmp.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        btnAddEmp.setText("Enter New Employee Information");
        btnAddEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddEmpMouseClicked(evt);
            }
        });

        btnViewModifyEmp.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        btnViewModifyEmp.setText("View/Modify Employee Information");
        btnViewModifyEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnViewModifyEmpMouseClicked(evt);
            }
        });

        btnCreateDailyRpt.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        btnCreateDailyRpt.setText("Create Daily Report");
        btnCreateDailyRpt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCreateDailyRptMouseClicked(evt);
            }
        });
        btnCreateDailyRpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateDailyRptActionPerformed(evt);
            }
        });

        btnLogout.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
        });
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnViewModifyEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCreateDailyRpt, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnAddEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewModifyEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCreateDailyRpt, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddEmpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddEmpMouseClicked
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAddNewEmp().setVisible(true);
            }
        });
    }//GEN-LAST:event_btnAddEmpMouseClicked

    private void btnViewModifyEmpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewModifyEmpMouseClicked
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSelectEmp().setVisible(true);
            }
        });


    }//GEN-LAST:event_btnViewModifyEmpMouseClicked

    private void btnCreateDailyRptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreateDailyRptMouseClicked
        // TODO add your handling code here:
        String url = "jdbc:mysql://localhost:3306/";
        String dbName = "ad";
        String driver = "com.mysql.jdbc.Driver";
        String userName = "root";
        String password = "";
        try {

            PrintWriter writer;
            PrintWriter nWriter;
            PreparedStatement ps = null;

            Class.forName(driver).newInstance();

            Connection conn = DriverManager.getConnection(url + dbName, userName, password);
            Statement st = conn.createStatement();
            DateFormat today = new SimpleDateFormat("yyyy-MM-dd");
            Date todaysDate = new Date();
            ResultSet EmployeesTable = st.executeQuery("Select ad.columns, ad.title, category.catName, ad.publishDate, ad.adID, ad.contents, "
                    + "client.companyName, client.phone, paymentPlan.balance, paymentPlan.totalAmountPayed, paymentPlan.planID, paymentPlan.planName from category, ad, paymentPlan,"
                    + " client where ad.publishDate ='" + today.format(todaysDate) + " 00:00:00' and ad.clientID=client.clientID and ad.planID=paymentPlan.planID and ad.catID=category.catID");
            Component frame = null;
            SimpleDateFormat DateFormat;
            Date currentDate = new Date();
            String currDate = new SimpleDateFormat("yyyy-MM-dd      HH-mm-ss").format(currentDate);
            File paid=new File("Pagination logs");
            File unpaid=new File("Daily reports");
            if (!paid.exists()){
                paid.mkdir();
            }
            if(!unpaid.exists()){
                unpaid.mkdir();
            }
             
            writer = new PrintWriter("Daily reports\\Unpaid Ad Report " + currDate + ".txt", "UTF-8");
            writer.println("\t\t\t\t\tUnpaid Ad Report \n " + "\t\t\t\t  " + currDate);
            nWriter = new PrintWriter("Pagination logs\\Paid Ad Report " + currDate + ".txt", "UTF-8");
            nWriter.println("\t\t\t\tAd's sent to Pagination System \n " + "\t\t\t\t" + currDate);
            NumberFormat formatter=NumberFormat.getCurrencyInstance();
            
            while (EmployeesTable.next()) {
                String contents = EmployeesTable.getString("contents");
                int lines = contents.length() / 20;
                double totalBalance = 0;

                if (EmployeesTable.getDouble("balance") - EmployeesTable.getDouble("paymentPlan.totalAmountPayed") == 0) {
                    nWriter.println("AD ID#: " + EmployeesTable.getString("adID"));
                    nWriter.println("Category: " + EmployeesTable.getString("catName"));
                    nWriter.println("Title: " + EmployeesTable.getString("title"));
                    nWriter.println("Content: " + EmployeesTable.getString("contents"));
                    nWriter.println("Columns: " + EmployeesTable.getString("columns"));
                    nWriter.println("Size: " + lines + 1);

                    nWriter.println("\n\n\n");

                }
                if (EmployeesTable.getDouble("balance") - EmployeesTable.getDouble("paymentPlan.totalAmountPayed") > 0) {
                    writer.println("AD ID#: " + EmployeesTable.getString("adID"));
                    writer.println("Contents: " + EmployeesTable.getString("contents"));
                    writer.println("Customer: " + EmployeesTable.getString("companyName"));
                    writer.println("Phone#: " + EmployeesTable.getString("phone"));
                    writer.println("planID: " + EmployeesTable.getInt("planID"));
                    writer.println("\n\n\n");
                }

            }
            nWriter.close();
            writer.println("\n\n\n");
            writer.println("TOTALS:\n");
            writer.println("PlanID\t\t\tPlan Name\t\t\tPlan Total\t\tTotal Amount Owed");
            writer.println("--------------------------------------------------------------------------------------------------------");
            EmployeesTable.beforeFirst();
            ArrayList<Integer> printedIDs =new ArrayList<Integer>();
            double sum=0;
            while(EmployeesTable.next())
            {
                if((EmployeesTable.getDouble("balance") - EmployeesTable.getDouble("paymentPlan.totalAmountPayed") > 0)){
                    if (!printedIDs.contains(EmployeesTable.getInt("planID")))
                    {
                        printedIDs.add(EmployeesTable.getInt("planID"));
                        writer.print(EmployeesTable.getInt("planID")+"\t\t\t"+EmployeesTable.getString("planName")+"\t\t\t"+formatter.format(EmployeesTable.getDouble("balance"))+"\t\t\t"+formatter.format((EmployeesTable.getDouble("balance")-EmployeesTable.getDouble("totalAmountPayed")))+"");
                        writer.println();
                        sum+=(EmployeesTable.getDouble("balance")-EmployeesTable.getDouble("totalAmountPayed"));
                    }
                }
            }
            writer.println("Total Owed: "+formatter.format(sum));
            writer.close();
            JOptionPane.showMessageDialog(frame, "The AD Report has been Generated");
            conn.close();
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException e) {
            e.printStackTrace();
        } catch (FileNotFoundException | UnsupportedEncodingException ex) {
            Logger.getLogger(frmITMode.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnCreateDailyRptMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
        // TODO add your handling code here:

        int reply = JOptionPane.showConfirmDialog(null,
                "Are you sure you want to Logout?", null, JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            this.setVisible(false);
            this.dispose();
            new frmUserSelection().setVisible(true);
        }


    }//GEN-LAST:event_btnLogoutMouseClicked

    private void btnCreateDailyRptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateDailyRptActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnCreateDailyRptActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmITMode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmITMode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmITMode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmITMode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmITMode().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddEmp;
    private javax.swing.JButton btnCreateDailyRpt;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnViewModifyEmp;
    // End of variables declaration//GEN-END:variables
}
