
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Justin
 */
public class frmManagerMode extends javax.swing.JFrame {
private int empID;
public void setempID(int IDNum)
{
    empID=IDNum;
}
    /**
     * Creates new form frmManagerMode
     */
    public frmManagerMode() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnViewModifyClientInfo = new javax.swing.JButton();
        btnEnterNewClientInfo = new javax.swing.JButton();
        btnEnerNewAdInfo = new javax.swing.JButton();
        btnViewModifyAdInfo = new javax.swing.JButton();
        btnAddCategories = new javax.swing.JButton();
        btnModifyCat = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manager Mode");
        setResizable(false);

        btnViewModifyClientInfo.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        btnViewModifyClientInfo.setText("View/Modify client information");
        btnViewModifyClientInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnViewModifyClientInfoMouseClicked(evt);
            }
        });
        btnViewModifyClientInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewModifyClientInfoActionPerformed(evt);
            }
        });

        btnEnterNewClientInfo.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        btnEnterNewClientInfo.setText("Enter new client information");
        btnEnterNewClientInfo.setBorder(null);
        btnEnterNewClientInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEnterNewClientInfoMouseClicked(evt);
            }
        });
        btnEnterNewClientInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterNewClientInfoActionPerformed(evt);
            }
        });

        btnEnerNewAdInfo.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        btnEnerNewAdInfo.setText("Enter new ad information");
        btnEnerNewAdInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEnerNewAdInfoMouseClicked(evt);
            }
        });

        btnViewModifyAdInfo.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        btnViewModifyAdInfo.setText("View/Modify ad information");
        btnViewModifyAdInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnViewModifyAdInfoMouseClicked(evt);
            }
        });

        btnAddCategories.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        btnAddCategories.setText("Add a Category");
        btnAddCategories.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddCategoriesMouseClicked(evt);
            }
        });

        btnModifyCat.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        btnModifyCat.setText("View/Modify Category");
        btnModifyCat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModifyCatMouseClicked(evt);
            }
        });
        btnModifyCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyCatActionPerformed(evt);
            }
        });

        btnLogout.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
        });
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEnterNewClientInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addComponent(btnViewModifyClientInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addComponent(btnEnerNewAdInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addComponent(btnViewModifyAdInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addComponent(btnAddCategories, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addComponent(btnModifyCat, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))
                .addGap(0, 40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btnEnterNewClientInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewModifyClientInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEnerNewAdInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewModifyAdInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddCategories, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnModifyCat, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewModifyClientInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewModifyClientInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewModifyClientInfoActionPerformed

    private void btnEnterNewClientInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnterNewClientInfoMouseClicked
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmNewClientInfo().setVisible(true);
            }
        });
    }//GEN-LAST:event_btnEnterNewClientInfoMouseClicked

    private void btnAddCategoriesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddCategoriesMouseClicked
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmNewCat().setVisible(true);
            }
        });
    }//GEN-LAST:event_btnAddCategoriesMouseClicked

    private void btnViewModifyClientInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewModifyClientInfoMouseClicked
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSelectClient().setVisible(true);
            }
        });
    }//GEN-LAST:event_btnViewModifyClientInfoMouseClicked

    private void btnModifyCatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModifyCatMouseClicked
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSelectCat().setVisible(true);
            }
        });
    }//GEN-LAST:event_btnModifyCatMouseClicked

    private void btnModifyCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyCatActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnModifyCatActionPerformed

    private void btnEnterNewClientInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterNewClientInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEnterNewClientInfoActionPerformed

    private void btnEnerNewAdInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnerNewAdInfoMouseClicked
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmNewAd().setVisible(true);
            }
        });
    }//GEN-LAST:event_btnEnerNewAdInfoMouseClicked

    private void btnViewModifyAdInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewModifyAdInfoMouseClicked
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSelectAd().setVisible(true);
            }
        });
    }//GEN-LAST:event_btnViewModifyAdInfoMouseClicked

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
        // TODO add your handling code here:
        
         int reply = JOptionPane.showConfirmDialog(null,
                "Are you sure you want to Logout?", null, JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
             this.setVisible(false);
        this.dispose();
        new frmUserSelection().setVisible(true);
        }
        
        
      

    }//GEN-LAST:event_btnLogoutMouseClicked

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmManagerMode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmManagerMode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmManagerMode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmManagerMode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmManagerMode().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCategories;
    private javax.swing.JButton btnEnerNewAdInfo;
    private javax.swing.JButton btnEnterNewClientInfo;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnModifyCat;
    private javax.swing.JButton btnViewModifyAdInfo;
    private javax.swing.JButton btnViewModifyClientInfo;
    // End of variables declaration//GEN-END:variables
}
