
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author NABAIN
 */
public class frmModifyEmp extends javax.swing.JFrame {
    private int empID;
    public void setEmpID(int SelectedID)
    {
        this.empID=SelectedID;
    }
    /**
     * Creates new form frmModifyEmp
     */
    public frmModifyEmp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFirstName = new javax.swing.JTextField();
        lblFirstName = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        lblEmpPosition = new javax.swing.JLabel();
        cmboEmpPosition = new javax.swing.JComboBox();
        btnSubmit = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modify Employee Information");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        txtFirstName.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        txtFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstNameActionPerformed(evt);
            }
        });

        lblFirstName.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        lblFirstName.setText("First Name *");

        lblLastName.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        lblLastName.setText("Last Name *");

        txtLastName.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N

        lblEmpPosition.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        lblEmpPosition.setText("Employee Position *");

        cmboEmpPosition.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        cmboEmpPosition.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnSubmit.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSubmitMouseClicked(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblLastName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFirstName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEmpPosition)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addComponent(cmboEmpPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstName)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLastName)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmpPosition)
                    .addComponent(cmboEmpPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmit)
                    .addComponent(btnCancel))
                .addGap(41, 41, 41))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubmitMouseClicked
        // TODO add your handling code here:
        String url = "jdbc:mysql://localhost:3306/";
		  String dbName = "ad";
		  String driver = "com.mysql.jdbc.Driver";
		  String userName = "root"; 
		  String password = "";
		  try {
                      Class.forName(driver).newInstance();
                      Connection conn = DriverManager.getConnection(url+dbName,userName,password);
                      Statement st= conn.createStatement();
                      String queryText="UPDATE employee SET ";
                      if(txtFirstName.getText()!="" && txtLastName.getText()!=""){
                          queryText+="empFirstName='"+txtFirstName.getText()+"', empLastName='"+txtLastName.getText()+"'";
                          if(cmboEmpPosition.getSelectedIndex()!=0)
                          {
                              if(cmboEmpPosition.getSelectedIndex()==1)
                              {
                                  queryText+=", empType='Normal'";
                              }else if(cmboEmpPosition.getSelectedIndex()==2){
                                  queryText+=", empType='Manager'";
                              }else{
                                  queryText+=", empType='IT'";
                              }
                          }else{
                              queryText+=", empType=null";
                          }
                      }
                      queryText+= " WHERE empID="+this.empID;
                      
                     int counter = 0;
                      if(txtFirstName.getText().equals("")){
                          lblFirstName.setForeground(Color.RED);
                          counter++;
                      }
                      if(txtLastName.getText().equals("")){
                          lblLastName.setForeground(Color.RED);
                          counter++;
                      }
                      if(cmboEmpPosition.getSelectedIndex() == 0){
                          lblEmpPosition.setForeground(Color.RED);
                          counter++;
                      }
                      
                      if(counter ==0){
                      st.executeUpdate(queryText);
                      
                      java.awt.EventQueue.invokeLater(new Runnable() {
                    public void run() {
                    new frmSuccessWindow().setVisible(true);
                    }
                  });
                     this.setVisible(false);
                  this.dispose();
                  
                      }
                      
                      
                       if (counter > 0) {
                java.awt.EventQueue.invokeLater(new Runnable() {
                    public void run() {
                        new frmMissingInfo().setVisible(true);
                    }
                });
            }
                      
                      
                      conn.close();
		  } catch (Exception e) {
		  e.printStackTrace();
                  }
                  
                  
                  
                  
                  
                  
                  
                  
    }//GEN-LAST:event_btnSubmitMouseClicked

    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
        // TODO add your handling code here:
       
        int reply = JOptionPane.showConfirmDialog(null,
                "Are you sure you want to cancel?", null, JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
             this.setVisible(false);
                  this.dispose();
        }
        
       
    }//GEN-LAST:event_btnCancelMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        String url = "jdbc:mysql://localhost:3306/";
		  String dbName = "ad";
		  String driver = "com.mysql.jdbc.Driver";
		  String userName = "root"; 
		  String password = "";
		  try {
                      Class.forName(driver).newInstance();
                      Connection conn = DriverManager.getConnection(url+dbName,userName,password);
                      Statement st= conn.createStatement();
                      String queryText="SELECT * FROM employee WHERE empID="+this.empID;
                      ResultSet clientTable=st.executeQuery(queryText);
                      cmboEmpPosition.removeAllItems();
                      cmboEmpPosition.addItem("      ");
                      cmboEmpPosition.addItem("Normal");
                      cmboEmpPosition.addItem("Manager");
                      cmboEmpPosition.addItem("IT");
                      if (clientTable.next())
                      {
                          
                          txtFirstName.setText(clientTable.getString("empFirstName"));
                          txtLastName.setText(clientTable.getString("empLastName"));
                          
                          String employeeType=clientTable.getString("empType");
                          if(employeeType==(null))
                          {
                              cmboEmpPosition.setSelectedIndex(0);
                          }else if(employeeType.equals("Normal")){
                              cmboEmpPosition.setSelectedItem("Normal");
                          }else if(employeeType.equals("Manager")){
                              cmboEmpPosition.setSelectedItem("Manager");
                          }else if(employeeType.equals("IT")){
                              cmboEmpPosition.setSelectedItem("IT");
                          }
                      }else{
                        System.err.println("No record found.");
                      }
                      conn.close();
		  } catch (Exception e) {
		  e.printStackTrace();
                  }
    }//GEN-LAST:event_formWindowOpened

    private void txtFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmModifyEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmModifyEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmModifyEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmModifyEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
   
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmModifyEmp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox cmboEmpPosition;
    private javax.swing.JLabel lblEmpPosition;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    // End of variables declaration//GEN-END:variables
}
