//Checked out by Adam Pyle

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Adam
 */
public class frmModifyClient extends javax.swing.JFrame {

    private int clientID;

    public void setClientID(int SelectedID) {
        this.clientID = SelectedID;
    }

    /**
     * Creates new form frmModifyClient
     */
    public frmModifyClient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPhoneNumber = new javax.swing.JTextField();
        txtCompanyName = new javax.swing.JTextField();
        phone = new javax.swing.JLabel();
        company = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        billAddress = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtBillingAddress = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        txtCreditCardNumber = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cmbCreditCardType = new javax.swing.JComboBox();
        btnSaveChanges = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modify Client Information");
        setMinimumSize(new java.awt.Dimension(535, 448));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        txtPhoneNumber.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N

        txtCompanyName.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        txtCompanyName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCompanyNameActionPerformed(evt);
            }
        });

        phone.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        phone.setText("Phone Number *");

        company.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        company.setText("Company Name *");

        address.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        address.setText("Client Address *");

        billAddress.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        billAddress.setText("Billing Address *");

        txtAddress.setColumns(20);
        txtAddress.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        txtAddress.setLineWrap(true);
        txtAddress.setRows(5);
        txtAddress.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtAddress);

        txtBillingAddress.setColumns(20);
        txtBillingAddress.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        txtBillingAddress.setLineWrap(true);
        txtBillingAddress.setRows(5);
        txtBillingAddress.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txtBillingAddress);

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel7.setText("Credit Card Number:");

        txtCreditCardNumber.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        txtCreditCardNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCreditCardNumberActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel8.setText("Credit Card Type:");

        cmbCreditCardType.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        cmbCreditCardType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnSaveChanges.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        btnSaveChanges.setText("Save Changes");
        btnSaveChanges.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveChangesMouseClicked(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
        });
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jCheckBox1.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jCheckBox1.setText("same as address");
        jCheckBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox1MouseClicked(evt);
            }
        });
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSaveChanges, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(company)
                        .addGap(73, 73, 73)
                        .addComponent(txtCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(billAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jCheckBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbCreditCardType, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCreditCardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(company))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phone)
                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(address))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(billAddress)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox1))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel7))
                    .addComponent(txtCreditCardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(cmbCreditCardType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveChanges)
                    .addComponent(btnCancel))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        String url = "jdbc:mysql://localhost:3306/";
        String dbName = "ad";
        String driver = "com.mysql.jdbc.Driver";
        String userName = "root";
        String password = "";
        try {
            Class.forName(driver).newInstance();
            Connection conn = DriverManager.getConnection(url + dbName, userName, password);
            Statement st = conn.createStatement();
            String queryText = "SELECT * FROM client WHERE clientID=" + this.clientID;
            ResultSet clientTable = st.executeQuery(queryText);
            cmbCreditCardType.removeAllItems();
            cmbCreditCardType.addItem("      ");
            cmbCreditCardType.addItem("Master Card");
            cmbCreditCardType.addItem("Visa");
            cmbCreditCardType.addItem("Discovery Card");
            if (clientTable.next()) {

                txtCompanyName.setText(clientTable.getString("companyName"));
                txtPhoneNumber.setText(clientTable.getString("phone"));
                txtAddress.setText(clientTable.getString("address"));
                if (clientTable.getString("billingAddress") != null) {
                    txtBillingAddress.setText(clientTable.getString("billingAddress"));
                } else {
                    txtBillingAddress.setText("");
                }
                if (clientTable.getString("creditCard") != null) {
                    txtCreditCardNumber.setText(String.valueOf(clientTable.getBigDecimal("creditCard")));
                } else {
                    txtCreditCardNumber.setText("");
                }
                String creditCardType = clientTable.getString("creditCardType");
                if (creditCardType == (null)) {
                    cmbCreditCardType.setSelectedIndex(0);
                } else if (creditCardType.equals("Master Card")) {
                    cmbCreditCardType.setSelectedItem("Master Card");
                } else if (creditCardType.equals("Visa")) {
                    cmbCreditCardType.setSelectedItem("Visa");
                } else if (creditCardType.equals("Discovery Card")) {
                    cmbCreditCardType.setSelectedItem("Discovery Card");
                }
            } else {
                System.err.println("No record found.");
            }
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_formWindowOpened

    private void txtCompanyNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCompanyNameActionPerformed

    }//GEN-LAST:event_txtCompanyNameActionPerformed

    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked

        int reply = JOptionPane.showConfirmDialog(null,
                "Are you sure you want to Cancel?", null, JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            this.setVisible(false);
            this.dispose();
        }

    }//GEN-LAST:event_btnCancelMouseClicked

    private void btnSaveChangesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveChangesMouseClicked
        String url = "jdbc:mysql://localhost:3306/";
        String dbName = "ad";
        String driver = "com.mysql.jdbc.Driver";
        String userName = "root";
        String password = "";
        try {
            Class.forName(driver).newInstance();
            Connection conn = DriverManager.getConnection(url + dbName, userName, password);
            Statement st = conn.createStatement();
            String queryText = "UPDATE client SET ";
            if (txtCompanyName.getText() != "" && txtPhoneNumber.getText() != "" && txtAddress.getText() != "") {
                queryText += "companyName='" + txtCompanyName.getText() + "', phone='" + txtPhoneNumber.getText() + "', address='" + txtAddress.getText() + "'";
                if (!txtBillingAddress.getText().equals("")) {
                    queryText += ", billingAddress='" + txtBillingAddress.getText() + "'";
                } else {
                    queryText += ", billingAddress=null";
                }
                if (!txtCreditCardNumber.getText().equals("")) {
                    queryText += ", creditCard='" + txtCreditCardNumber.getText() + "'";
                } else {
                    queryText += ", creditCard=null";
                }
                if (cmbCreditCardType.getSelectedIndex() != 0) {
                    if (cmbCreditCardType.getSelectedIndex() == 1) {
                        queryText += ", creditCardType='Master Card'";
                    } else if (cmbCreditCardType.getSelectedIndex() == 2) {
                        queryText += ", creditCardType='Visa'";
                    } else {
                        queryText += ", creditCardType='Discover Card'";
                    }
                } else {
                    queryText += ", creditCardType=null";
                }
            }
            queryText += " WHERE clientID=" + this.clientID;
            
            int counter = 0;
            String pattern= "[0-9]+";
            
            if (!txtPhoneNumber.getText().matches(pattern)){
                    phone.setForeground(Color.RED);
                    JFrame frame = new JFrame();
                JOptionPane.showMessageDialog(frame, "Phone number must be numerical");
                
                }
            
            if (txtPhoneNumber.getText().equals("")) {
                phone.setForeground(Color.RED);
            counter ++;
            }
            if (txtCompanyName.getText().equals("")) {
                company.setForeground(Color.RED);
              counter ++;  
            }
            
            if (txtAddress.getText().equals("")) {
                address.setForeground(Color.RED);
                counter ++;
            }
            if (txtBillingAddress.getText().equals("")) {
                billAddress.setForeground(Color.RED);
              counter++;  
            }
            
            
            
                if(counter == 0){
            st.executeUpdate(queryText);
            
              java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSuccessWindow().setVisible(true);
            }
        });

        this.setVisible(false);
        this.dispose();
            
                }
                
                if(counter > 0){
                       java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMissingInfo().setVisible(true);
            }
        });
            }
                
                
              conn.close();  
                
        } catch (Exception e) {
            e.printStackTrace();
        }
        

      
    }//GEN-LAST:event_btnSaveChangesMouseClicked

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtCreditCardNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCreditCardNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCreditCardNumberActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox1MouseClicked
        // TODO add your handling code here:
        txtBillingAddress.setText(txtAddress.getText());

    }//GEN-LAST:event_jCheckBox1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmModifyClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmModifyClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmModifyClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmModifyClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmModifyClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel address;
    private javax.swing.JLabel billAddress;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSaveChanges;
    private javax.swing.JComboBox cmbCreditCardType;
    private javax.swing.JLabel company;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel phone;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextArea txtBillingAddress;
    private javax.swing.JTextField txtCompanyName;
    private javax.swing.JTextField txtCreditCardNumber;
    private javax.swing.JTextField txtPhoneNumber;
    // End of variables declaration//GEN-END:variables
}
