/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Sarah
 */
import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class frmNewCat extends javax.swing.JFrame {

    /**
     * Creates new form frmNewCat
     */
    public frmNewCat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        theCategory = new javax.swing.JTextField();
        submitCategory = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add a New Category");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel1.setText("Enter the name of a new category:");

        theCategory.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        theCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                theCategoryActionPerformed(evt);
            }
        });

        submitCategory.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        submitCategory.setText("Submit");
        submitCategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitCategoryMouseClicked(evt);
            }
        });
        submitCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitCategoryActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(submitCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(theCategory)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(theCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitCategory)
                    .addComponent(btnCancel))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(389, 194));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void theCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_theCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_theCategoryActionPerformed

    private void submitCategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitCategoryMouseClicked
        // TODO add your handling code here:
        String url = "jdbc:mysql://localhost:3306/";
        String dbName = "ad";
        String driver = "com.mysql.jdbc.Driver";
        String userName = "root";
        String password = "";

        try {
            Class.forName(driver).newInstance();
            Connection conn = DriverManager.getConnection(url + dbName, userName, password);
            Statement st = conn.createStatement();
            
            ResultSet EmployeesTable=st.executeQuery("select catName from category");
            while (EmployeesTable.next()){
                if (theCategory.getText().equals(EmployeesTable.getString("catName"))){
                JFrame frame = new JFrame();
                JOptionPane.showMessageDialog(frame, "Please enter a new category");
                java.awt.EventQueue.invokeLater(new Runnable() {
                    public void run() {
                        new frmNewCat().setVisible(true);
                    }
                }
                );
                this.setVisible(false);
                        this.dispose();
            }
            }
            
            String queryText = "INSERT INTO category (catName) VALUES ('" + theCategory.getText() + "')";
            if (theCategory.getText().equals("")) {
                JFrame frame = new JFrame();
                JOptionPane.showMessageDialog(frame, "Please enter a new category");
                java.awt.EventQueue.invokeLater(new Runnable() {
                    public void run() {
                        new frmNewCat().setVisible(true);
                    }
                });

            } else {
                st.executeUpdate(queryText);
                java.awt.EventQueue.invokeLater(new Runnable() {
                    public void run() {
                        new frmSuccessWindow().setVisible(true);
                       
                    }
                });
            }
            

            //TODO: finish null cases for credit card info or lack therof
            theCategory.setText("");

            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }

        


    }//GEN-LAST:event_submitCategoryMouseClicked

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
       
        int reply = JOptionPane.showConfirmDialog(null,
                "Are you sure you want to Cancel?", null, JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
             this.setVisible(false);
        this.dispose();
        }
    }//GEN-LAST:event_btnCancelActionPerformed

    private void submitCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_submitCategoryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmNewCat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmNewCat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmNewCat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmNewCat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmNewCat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton submitCategory;
    private javax.swing.JTextField theCategory;
    // End of variables declaration//GEN-END:variables
}
